# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 8bithe.art
email: john@rineysoft.com
description: "Blogs are still cool, right?"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rineysoft.com" # the base hostname & protocol for your site
github_username: riney
instagram_username: rin3y
linkedin_username: riney
excerpt_separator: <!-- more -->

# Build settings
markdown: kramdown
